# Generated by Django 3.2.3 on 2021-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Sname', models.CharField(max_length=32)),
                ('Sscore', models.FloatField()),
                ('Saddr', models.CharField(max_length=64)),
            ],
        ),
    ]
