# Generated by Django 3.2.3 on 2021-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eno', models.IntegerField()),
                ('Ename', models.CharField(max_length=32)),
                ('Escore', models.FloatField()),
                ('Eaddr', models.CharField(max_length=64)),
            ],
        ),
    ]
