# Generated by Django 3.2.3 on 2021-05-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Eaddr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Saddr',
        ),
    ]
