# Generated by Django 3.2.3 on 2021-05-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210523_0612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
